name: Build and deploy

on:
  push:
    branches: [teste]
  pull_request:
    branches: [teste]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create temporary SSH key filee
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
      - name: Deploy NestApp
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key_path: ./ssh_key
          script: |
            rm -rf meformei-app/main/backend
            mkdir meformei-app
            cd meformei-app
            mkdir main/
            cd main/
            git clone -b teste https://github.com/preciousakura/me.formei-backend.git backend
            cd backend
            npm i
            npm run build
            pm2 stop "me-formei-backend"
            pm2 delete "me-formei-backend"
            pm2 start dist/main.js --name "me-formei-backend"
            pm2 save
